export type Restoran = {
  slug: string;
  ad: string;
  mutfaklar: string[];
  puan: number;
  yorum: number;
  /** [en hızlı, en yavaş] tahmini teslimat süresi, dakika. */
  sureDk: [number, number];
  minSepet: number;
  /** 0 → teslimat ücretsiz */
  teslimatUcreti: number;
  kampanya?: string;
  etiketler: string[];
  sehir: string;
  semt: string;
  oneCikan?: boolean;
};

export const restoranlar: Restoran[] = [
  {
    slug: "ates-kanat",
    ad: "Ateş Kanat",
    mutfaklar: ["Tavuk", "Kanat", "Fast Food"],
    puan: 4.7,
    yorum: 2841,
    sureDk: [25, 35],
    minSepet: 120,
    teslimatUcreti: 0,
    kampanya: "2 alana 1 bedava kanat",
    etiketler: ["Süper Hızlı", "Ücretsiz Teslimat"],
    sehir: "İstanbul",
    semt: "Kadıköy",
    oneCikan: true,
  },
  {
    slug: "kirmizi-firin",
    ad: "Kırmızı Fırın",
    mutfaklar: ["Pizza", "İtalyan"],
    puan: 4.8,
    yorum: 5127,
    sureDk: [30, 45],
    minSepet: 150,
    teslimatUcreti: 0,
    kampanya: "%30 indirim — tüm pizzalarda",
    etiketler: ["Editörün Seçimi", "Ücretsiz Teslimat"],
    sehir: "İstanbul",
    semt: "Beşiktaş",
    oneCikan: true,
  },
  {
    slug: "sef-mangal",
    ad: "Şef Mangal",
    mutfaklar: ["Kebap", "Izgara", "Meze"],
    puan: 4.6,
    yorum: 3392,
    sureDk: [35, 50],
    minSepet: 200,
    teslimatUcreti: 19,
    kampanya: "200 TL üzeri siparişe ayran ikram",
    etiketler: ["Odun Ateşi"],
    sehir: "Ankara",
    semt: "Çankaya",
    oneCikan: true,
  },
  {
    slug: "anne-sofrasi",
    ad: "Anne Sofrası",
    mutfaklar: ["Ev Yemekleri", "Çorba", "Türk Mutfağı"],
    puan: 4.9,
    yorum: 6084,
    sureDk: [20, 30],
    minSepet: 90,
    teslimatUcreti: 0,
    kampanya: "Günün çorbası 1 TL",
    etiketler: ["En Yüksek Puan", "Süper Hızlı", "Ücretsiz Teslimat"],
    sehir: "İzmir",
    semt: "Bornova",
    oneCikan: true,
  },
  {
    slug: "burger-atolyesi",
    ad: "Burger Atölyesi",
    mutfaklar: ["Burger", "Fast Food"],
    puan: 4.5,
    yorum: 1978,
    sureDk: [25, 40],
    minSepet: 140,
    teslimatUcreti: 14,
    kampanya: "Menü yükseltme ücretsiz",
    etiketler: ["Yeni"],
    sehir: "İstanbul",
    semt: "Şişli",
  },
  {
    slug: "doner-vadisi",
    ad: "Döner Vadisi",
    mutfaklar: ["Döner", "Dürüm"],
    puan: 4.4,
    yorum: 4410,
    sureDk: [15, 25],
    minSepet: 70,
    teslimatUcreti: 9,
    kampanya: "Porsiyon dönere patates ikram",
    etiketler: ["Süper Hızlı", "Bütçe Dostu"],
    sehir: "Bursa",
    semt: "Nilüfer",
  },
  {
    slug: "tatli-kacamak",
    ad: "Tatlı Kaçamak",
    mutfaklar: ["Tatlı", "Pasta", "Dondurma"],
    puan: 4.8,
    yorum: 2265,
    sureDk: [30, 45],
    minSepet: 110,
    teslimatUcreti: 0,
    kampanya: "İkinci dilim yarı fiyat",
    etiketler: ["Ücretsiz Teslimat"],
    sehir: "İstanbul",
    semt: "Bakırköy",
  },
  {
    slug: "cekirdek-kahve",
    ad: "Çekirdek Kahve",
    mutfaklar: ["Kahve", "Sandviç", "Kahvaltı"],
    puan: 4.7,
    yorum: 1542,
    sureDk: [15, 25],
    minSepet: 60,
    teslimatUcreti: 12,
    etiketler: ["Süper Hızlı", "Sabah Servisi"],
    sehir: "Ankara",
    semt: "Kızılay",
  },
  {
    slug: "deniz-kenari",
    ad: "Deniz Kenarı",
    mutfaklar: ["Balık", "Meze", "Deniz Ürünleri"],
    puan: 4.6,
    yorum: 987,
    sureDk: [40, 60],
    minSepet: 250,
    teslimatUcreti: 25,
    etiketler: ["Günlük Taze"],
    sehir: "İzmir",
    semt: "Alsancak",
  },
  {
    slug: "yesil-kase",
    ad: "Yeşil Kase",
    mutfaklar: ["Vegan", "Salata", "Sağlıklı"],
    puan: 4.5,
    yorum: 743,
    sureDk: [20, 30],
    minSepet: 100,
    teslimatUcreti: 0,
    kampanya: "İlk siparişte %25 indirim",
    etiketler: ["Yeni", "Ücretsiz Teslimat"],
    sehir: "İstanbul",
    semt: "Beyoğlu",
  },
  {
    slug: "kars-cig-borek",
    ad: "Kars Çiğ Börek",
    mutfaklar: ["Çiğ Börek", "Hamur İşi"],
    puan: 4.7,
    yorum: 3106,
    sureDk: [20, 35],
    minSepet: 80,
    teslimatUcreti: 10,
    kampanya: "6 alana 1 bedava",
    etiketler: ["Bütçe Dostu"],
    sehir: "Antalya",
    semt: "Muratpaşa",
  },
  {
    slug: "pide-ustasi",
    ad: "Pide Ustası",
    mutfaklar: ["Pide & Lahmacun", "Türk Mutfağı"],
    puan: 4.4,
    yorum: 2588,
    sureDk: [25, 40],
    minSepet: 95,
    teslimatUcreti: 12,
    etiketler: ["Taş Fırın"],
    sehir: "Konya",
    semt: "Selçuklu",
  },
  {
    slug: "baharat-yolu",
    ad: "Baharat Yolu",
    mutfaklar: ["Dünya Mutfağı", "Hint", "Uzak Doğu"],
    puan: 4.6,
    yorum: 1129,
    sureDk: [35, 50],
    minSepet: 180,
    teslimatUcreti: 18,
    kampanya: "Ana yemeğe pilav ikram",
    etiketler: ["Editörün Seçimi"],
    sehir: "İstanbul",
    semt: "Ataşehir",
  },
  {
    slug: "sabah-simit",
    ad: "Sabah Simit",
    mutfaklar: ["Kahvaltı", "Börek", "Fırın"],
    puan: 4.3,
    yorum: 1863,
    sureDk: [15, 25],
    minSepet: 50,
    teslimatUcreti: 8,
    etiketler: ["Süper Hızlı", "Sabah Servisi", "Bütçe Dostu"],
    sehir: "Eskişehir",
    semt: "Tepebaşı",
  },
  {
    slug: "gece-lezzetleri",
    ad: "Gece Lezzetleri",
    mutfaklar: ["Fast Food", "Tost", "Çorba"],
    puan: 4.2,
    yorum: 2947,
    sureDk: [20, 35],
    minSepet: 75,
    teslimatUcreti: 11,
    kampanya: "00.00 sonrası %20 indirim",
    etiketler: ["Gece Açık"],
    sehir: "Adana",
    semt: "Seyhan",
  },
  {
    slug: "hizli-market",
    ad: "Hızlı Market",
    mutfaklar: ["Market", "Atıştırmalık", "İçecek"],
    puan: 4.5,
    yorum: 5731,
    sureDk: [10, 20],
    minSepet: 60,
    teslimatUcreti: 9,
    kampanya: "İki alana bir bedava atıştırmalık",
    etiketler: ["Süper Hızlı", "10 Dakikada Kapında"],
    sehir: "İstanbul",
    semt: "Maltepe",
  },
];

/** Ana sayfadaki filtre şeridinde kullanılan hızlı filtreler. */
export const hizliFiltreler = [
  { etiket: "Tümü", test: () => true },
  { etiket: "Ücretsiz Teslimat", test: (r: Restoran) => r.teslimatUcreti === 0 },
  { etiket: "Süper Hızlı", test: (r: Restoran) => r.sureDk[0] <= 20 },
  { etiket: "Kampanyalı", test: (r: Restoran) => Boolean(r.kampanya) },
  { etiket: "4.5 ve üzeri", test: (r: Restoran) => r.puan >= 4.5 },
  { etiket: "Yeni", test: (r: Restoran) => r.etiketler.includes("Yeni") },
] as const;

export const siralamalar = [
  { etiket: "Önerilen", uygula: (a: Restoran, b: Restoran) => b.puan * Math.log10(b.yorum) - a.puan * Math.log10(a.yorum) },
  { etiket: "Puan", uygula: (a: Restoran, b: Restoran) => b.puan - a.puan },
  { etiket: "Teslimat süresi", uygula: (a: Restoran, b: Restoran) => a.sureDk[0] - b.sureDk[0] },
  { etiket: "Min. sepet", uygula: (a: Restoran, b: Restoran) => a.minSepet - b.minSepet },
] as const;
